# Generated by Django 5.1.1 on 2024-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('investor', 'Investor'), ('startup', 'Startup')], max_length=50, unique=True),
        ),
    ]
