# Generated by Django 5.1.1 on 2024-10-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('investor', 'Investor'), ('startup', 'Startup')], default='default_role', max_length=50),
            preserve_default=False,
        ),
    ]
