version: '3'

services:
  # Django API server
  web:
    build: .
    command: >
      ./scripts/wait-for-it.sh db:5432 -- python /code/forum/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DEBUG}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    env_file:
      - .env

  # React application
  react:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - web

  # PostgreSQL database
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  # Redis for Celery
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  # Celery worker
  celery:
    build: .
    command: celery -A forum worker --loglevel=info
    volumes:
      - .:/code
    working_dir: /code/forum
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DEBUG}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env

  # Maildev for testing emails
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "${MAILDEV_SMTP_PORT}:1025"
      - "${MAILDEV_UI_PORT}:1080"

volumes:
  postgres_data:
