version: '3'

services:
  # Django API server
  web:
    build: .
    command: >
      ./scripts/wait-for-it.sh db:5432 -- python /code/forum/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DEBUG}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    env_file:
      - .env

  # React application
  react:
    build:
      context: ./forum/frontend
    volumes:
      - ./forum/frontend:/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - web

  # PostgreSQL database
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  # MongoDB database
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      - ME_CONFIG_BASICAUTH=false

  # Redis for Celery
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  # Celery worker
  celery:
    build: .
    command: celery -A forum worker --loglevel=info
    volumes:
      - .:/code
    working_dir: /code/forum
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DEBUG}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env

  # Maildev for testing emails
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "${MAILDEV_SMTP_PORT}:1025"
      - "${MAILDEV_UI_PORT}:1080"

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always

volumes:
  postgres_data:
  elasticsearch_data:
