# Generated by Django 5.1.1 on 2024-10-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        ('projects', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_project_updates', models.BooleanField(default=True)),
                ('push_project_updates', models.BooleanField(default=True)),
                ('email_startup_updates', models.BooleanField(default=True)),
                ('push_startup_updates', models.BooleanField(default=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('project_follow', 'Project follower or subscription change'), ('project_profile_change', 'Project profile updated'), ('startup_profile_update', 'Startup profile updated'), ('startup_follow', 'Startup follower or subscription change')], max_length=55)),
                ('initiator', models.CharField(choices=[('investor', 'Investor'), ('project', 'Project'), ('startup', 'Startup')], max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('redirection_url', models.URLField(blank=True, null=True)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='investors.investor')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.project')),
                ('startup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='startups.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_project_updates', models.BooleanField(default=True)),
                ('push_project_updates', models.BooleanField(default=True)),
                ('email_startup_updates', models.BooleanField(default=True)),
                ('push_startup_updates', models.BooleanField(default=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='startups.startup')),
            ],
        ),
    ]
