# Generated by Django 5.1.1 on 2024-10-13 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
        ('notifications', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investornotificationpreferences',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='investors.investor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(choices=[('project_follow', 'Project follower or subscription change'), ('project_profile_change', 'Project profile updated'), ('startup_profile_update', 'Startup profile updated'), ('startup_follow', 'Startup follower or subscription change'), ('investor_follow', 'Investor follows startup')], max_length=55),
        ),
        migrations.AlterField(
            model_name='startupnotificationpreferences',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='startups.startup'),
        ),
    ]
