# Generated by Django 5.1.1 on 2024-10-14 19:55

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_investornotificationpreferences_investor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expiration',
            field=models.DateTimeField(default=notifications.models.get_expiration_date),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='initiator',
            field=models.CharField(choices=[('investor', 'Investor'), ('project', 'Project'), ('startup', 'Startup'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(choices=[('project_follow', 'Project follower or subscription change'), ('project_profile_change', 'Project profile updated'), ('startup_profile_update', 'Startup profile updated'), ('startup_follow', 'Startup follower or subscription change'), ('investor_follow', 'Investor follows startup'), ('investor_profile_change', 'Investor profile updated')], max_length=55),
        ),
    ]
