# Generated by Django 5.1.1 on 2024-10-09 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('city_code', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('startup_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('required_funding', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('funding_stage', models.CharField(choices=[('Seed', 'Seed'), ('Series A', 'Series A'), ('Series B', 'Series B'), ('Series C', 'Series C'), ('IPO', 'Initial Public Offering')], default='Seed', max_length=20)),
                ('number_of_employees', models.PositiveIntegerField(null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('total_funding', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='startups.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
            },
        ),
    ]
