# Generated by Django 5.1.1 on 2024-10-29 11:59

import startups.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_industry_startup_industries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['name'], 'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=startups.models.CaseInsensitiveField(max_length=100, unique=True),
        ),
    ]
