# Generated by Django 5.1.1 on 2024-10-21 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_investorfollow'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('funding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funded_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('funded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('funding_type', models.CharField(choices=[('equity', 'Equity Funding'), ('loan', 'Loan Funding'), ('grant', 'Grant')], default='equity', max_length=20)),
                ('investment_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(db_index=True, max_length=255)),
                ('investor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='investors.investor')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed_projects', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project_id', 'investor_id'), name='unique_project_investor')],
            },
        ),
    ]
