# Generated by Django 5.1.1 on 2024-10-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_historicalproject'),
        ('projects', '0002_subscription'),
    ]

    operations = [
    ]
